name: diet_and_train_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rounded_progress_bar: "^0.2.0"
  bezier_chart: "^1.0.6"
  percent_indicator: "^2.1.1"
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.4+1
  flutter_signin_button: ^1.0.0
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true
#    weight: 700
  assets:
  - assets/images/